[project]
name = "collect_four_game"
version = "0.1.0"
description = "Collect four game for multiple players with gravitation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pytest>=8.3.5",
]
